version: '3.7'

services:
  tradeshop:
    build:
      args: # values for Dockerfile
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    environment:
      ENVIRONMENT: dev
    volumes:
      - ./logs/:/app/logs/

  gateway:
    build:
      args: # values for Dockerfile
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    volumes:
      - ./logs/:/app/logs/
    environment:
      ENVIRONMENT: dev
