version: '3.7'

services:
  reverse_proxy:
    container_name: reverse_proxy
    hostname: reverse_proxy
    image: nginx
    depends_on:
      - tradeshop
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    volumes:
      - ./nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /etc/ssl/private/:/etc/ssl/private/
      - /srv/frontend/:/srv/frontend/
    command: [nginx, '-g', 'daemon off;']
    environment:
      WITH_PROXY: 'True'
