version: '3.7'

services:
  tradeshop:
    build:
      context: .
      target: tradeshop
      args: # values for Dockerfile
        ENVIRONMENT: ${ENVIRONMENT:-prod}
    image: tradeshop
    container_name: tradeshop
    command: bash -c "cd src && gunicorn -w 4 -b 0.0.0.0:5050 main:app"
    depends_on:
      - gateway
    restart: on-failure
    volumes:
      - ./apps/fithm-service/:/app/src/
    environment:
      ENVIRONMENT: prod
      SECRET_KEY: ${TRADESHOP_SEC_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DEBUG: '${DEBUG}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      FITHM_USE_SMTP: '${FITHM_USE_SMTP}'
      FITHM_SMTP_HOST: '${FITHM_SMTP_HOST}'
      FITHM_SMTP_PORT: '${FITHM_SMTP_PORT}'
      FITHM_SMTP_USER: '${FITHM_SMTP_USER}'
      FITHM_SMTP_PASS: '${FITHM_SMTP_PASS}'
      FITHM_SMTP_SECURITY: '${FITHM_SMTP_SECURITY}'
      FITHM_QUOVO_KEY: '${FITHM_QUOVO_KEY}'
      FITHM_ADMIN_MAIL: '${FITHM_ADMIN_MAIL}'
      FITHM_ADMIN_PASS: '${FITHM_ADMIN_PASS}'
    ports:
      - 5050:5050

  gateway:
    build:
      context: .
      target: gateway
      args: # values for Dockerfile
        ENVIRONMENT: ${ENVIRONMENT:-prod}
    image: gateway
    container_name: gateway
    command: bash -c "cd src && gunicorn -w 4 -b 0.0.0.0:5000 main:app"
    depends_on:
      - database
    restart: on-failure
    volumes:
      - ./apps/fithm-gateway/:/app/src/
    environment:
      ENVIRONMENT: prod
      SECRET_KEY: '${GATEWAY_SEC_KEY}'
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DEBUG: '${DEBUG}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      FITHM_USE_SMTP: '${FITHM_USE_SMTP}'
      FITHM_SMTP_HOST: '${FITHM_SMTP_HOST}'
      FITHM_SMTP_PORT: '${FITHM_SMTP_PORT}'
      FITHM_SMTP_USER: '${FITHM_SMTP_USER}'
      FITHM_SMTP_PASS: '${FITHM_SMTP_PASS}'
      FITHM_SMTP_SECURITY: '${FITHM_SMTP_SECURITY}'
      FITHM_SERVICE_URL: '${FITHM_SERVICE_URL}'
      FITHM_ADMIN_MAIL: '${FITHM_ADMIN_MAIL}'
      FITHM_ADMIN_PASS: '${FITHM_ADMIN_PASS}'
    ports:
      - 5000:5000

  database:
    image: postgres:13.4-alpine
    container_name: postgres
    volumes:
      - ./data/postgres/:/var/lib/postgresql/
    restart: on-failure
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - 5432:5432

