"""Add unique constraints.

Revision ID: 43abb1894c41
Revises: 689f557be5ac
Create Date: 2022-06-24 00:12:45.966841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43abb1894c41'
down_revision = '689f557be5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("account_positions_account_id_symbol_key", 'account_positions', ['account_id', 'symbol'])
    op.create_unique_constraint("model_positions_model_id_symbol_key", 'model_positions', ['model_id', 'symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("model_positions_model_id_symbol_key", 'model_positions', type_='unique')
    op.drop_constraint("account_positions_account_id_symbol_key", 'account_positions', type_='unique')
    # ### end Alembic commands ###
