"""empty message

Revision ID: 4582c84fe985
Revises: 10dc8b0904b4
Create Date: 2022-06-24 14:21:42.768117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4582c84fe985'
down_revision = '10dc8b0904b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_positions', sa.Column('is_cash', sa.Boolean(), nullable=True))
    op.drop_constraint('cash_position_price', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'account_position_price_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_position_price_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cash_position_price', 'accounts', 'account_position_price', ['account_position_price_id'], ['id'])
    op.drop_column('account_positions', 'is_cash')
    # ### end Alembic commands ###
