"""empty message

Revision ID: cdc4a7130d06
Revises: aae4e14eacdd
Create Date: 2022-06-10 00:34:34.440715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc4a7130d06'
down_revision = 'aae4e14eacdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('active_portfolio', 'trade_portfolios', ['portfolio_id', 'active'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('active_portfolio', 'trade_portfolios', type_='unique')
    # ### end Alembic commands ###
