"""empty message

Revision ID: e35f495182a7
Revises: 16d44c4cab1d
Create Date: 2022-07-10 20:22:01.669155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35f495182a7'
down_revision = '16d44c4cab1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_positions', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_positions', sa.Column('price', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
