"""empty message

Revision ID: f2c82863df50
Revises: 
Create Date: 2022-06-09 23:37:21.544150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c82863df50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_portfolio')
    op.add_column('trade_portfolios', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('trades', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('trade_portfolios', 'active')
    op.create_table('trade_portfolio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='trade_portfolio_portfolio_id_fkey'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name='trade_portfolio_trade_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trade_portfolio_pkey')
    )
    # ### end Alembic commands ###
