"""empty message

Revision ID: fb388767bb32
Revises: e35f495182a7
Create Date: 2022-07-13 02:54:37.315610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb388767bb32'
down_revision = 'e35f495182a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_position_price', sa.Column('is_manual', sa.Boolean(), nullable=True))
    op.add_column('model_position_price', sa.Column('is_manual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_position_price', 'is_manual')
    op.drop_column('account_position_price', 'is_manual')
    # ### end Alembic commands ###
